global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

ping:
  entryPoint: health

entryPoints:
  web:
    address: ":80"
  direct-api:
    address: ":8000"
  health:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: vision-edge
    watch: true
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO

accessLog:
  format: json
